#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove the results and the mesh
cleanCase

# Remove other files
\rm -rf case.foam contact history testDie.msh 0/materials*
\rm -f constant/polyMesh/boundary*