#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
runApplication blockMesh
runApplication setMatFromCellZones
runApplication plasticNonLinSolidFoam
runApplication uncoupledDamage
