    const dimensionedScalar D1 = dimensionedScalar(damDict.lookup("D1"));
    const dimensionedScalar D2 = dimensionedScalar(damDict.lookup("D2"));
    const dimensionedScalar D3 = dimensionedScalar(damDict.lookup("D3"));
    const dimensionedScalar D4 = dimensionedScalar(damDict.lookup("D4"));
    const dimensionedScalar D5 = dimensionedScalar(damDict.lookup("D5"));
    const dimensionedScalar D6 = dimensionedScalar(damDict.lookup("D6"));

